[package]
name = "http-parse"
version = "0.1.0"
edition = "2021"

[dependencies]


[profile.release]
debug = true

[[example]]
name="server"
path="src/examples/server.rs"

[[example]]
name="client"
path="src/examples/client.rs"

[[test]]
name="tests"
path = "src/tests/parsing.rs"