[package]
name = "http-parse"
version = "0.1.0"
edition = "2021"

[dependencies]


[profile.release]
debug = true

[[example]]
name="server"
path="src/server.rs"

[[example]]
name="client"
path="src/client.rs"
